version: 2
jobs:
  python3:
    environment:
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: circleci/python:3.7-rc-stretch
    steps:
      - checkout
      - run:
          name: Installing Python dependencies
          command: |
              sudo pip install --upgrade pip pipenv
              pipenv install --dev -e .
      - run:
          name: Running tests
          command: |
              pipenv run py.test --cov-config .coveragerc --cov-report xml:$CIRCLE_TEST_REPORTS/coverage.xml --cov mygeotab --junitxml $CIRCLE_TEST_REPORTS/python3-test-results.xml tests/
      - run:
          name: Uploading code coverage results
          command: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: /tmp/circleci-test-results
  python2:
    environment:
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: circleci/python:2.7-stretch
    steps:
      - checkout
      - run:
          name: Installing Python dependencies
          command: |
              pip install virtualenv
              virtualenv venv
              . venv/bin/activate
              pip install .
              pip install -r dev-requirements.txt
      - run:
          name: Running tests
          command: |
              . venv/bin/activate
              py.test --junitxml $CIRCLE_TEST_REPORTS/python2-test-results.xml tests/
      - store_test_results:
          path: /tmp/circleci-test-results
  pypy2:
    environment:
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: pypy:2
    steps:
      - checkout
      - run:
          name: Installing Python dependencies
          command: |
              pip install virtualenv
              virtualenv venv
              . venv/bin/activate
              pip install .
              pip install -r dev-requirements.txt
      - run:
          name: Running tests
          command: |
              . venv/bin/activate
              py.test --junitxml $CIRCLE_TEST_REPORTS/pypy2-test-results.xml tests/
      - store_test_results:
          path: /tmp/circleci-test-results
workflows:
  version: 2
  test_all:
    jobs:
      - python3
      - python2
      - pypy2